# Generated by Django 2.2.1 on 2019-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
