# Generated by Django 2.2.1 on 2019-06-01 03:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190531_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter a content', verbose_name='Contenido'),
        ),
    ]
