# Generated by Django 2.2.1 on 2019-05-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=210, verbose_name='Título')),
                ('subtitle', models.CharField(help_text='Enter a subtitle', max_length=210, verbose_name='Subtítulo')),
                ('contet', models.TextField(help_text='Enter a content', verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, upload_to='services_images', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
    ]
