# Generated by Django 2.2.1 on 2019-05-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='contet',
            new_name='content',
        ),
    ]
