# Generated by Django 2.2.1 on 2019-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Enter a key', max_length=100, unique=True, verbose_name='Nombre clave')),
                ('name', models.CharField(help_text='Enter a name', max_length=210, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, help_text='Enter a url', max_length=210, null=True, verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'nombres',
                'verbose_name_plural': 'nombres',
                'ordering': ['name'],
            },
        ),
    ]
